spring:
 profiles:
  active: development
   
server:
 port: 8060

jasperSource:
 prefix: jasperreports/
 suffix: .jrxml
 reportDataKey: datasource
 viewName: report_*

application:
 version: @project.version@
 java_version: @project.version@
 
elasticsearch:
  port: 9300,
  host: localhost,
  clustername: bbt-cluster